# Example configuration for etsu

[database]
# Your postgres database url, if empty only local sqlite db will be used
postgres_url = "postgresql://user:password@host:port/{{db_name}}"

[intervals_ms]
# How often to calculate distance from latest mouse position (ms)
processing = 250
# How often to save metrics to the database (ms)
saving = 60000 # 60 seconds
# How often to update the system tray UI (ms)
ui_update = 5000 # 5 seconds

# Log level filter (e.g., "info", "warn")
log_level = "info"
